# Generated by Django 3.0.7 on 2020-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='distribution',
            field=models.CharField(default='0[None]500.501[None]', max_length=1000),
        ),
    ]
