# Generated by Django 3.0.7 on 2020-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_city_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='distribution',
            field=models.CharField(default='0-None-500.501-None-', max_length=1000),
        ),
    ]
